# Generated by Django 3.2.8 on 2021-10-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='категория статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
            ],
            options={
                'verbose_name': 'категория статьи',
                'verbose_name_plural': 'категории статей',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('image', models.ImageField(blank=True, upload_to='articles_images')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='тэг статьи')),
                ('hub', models.CharField(blank=True, max_length=64, verbose_name='хаб статьи')),
                ('add_datatime', models.DateField(auto_now_add=True, verbose_name='время добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.articlescategory')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
