# Generated by Django 3.2 on 2021-10-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название хаба')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
            ],
            options={
                'verbose_name': 'хаб',
                'verbose_name_plural': 'хабы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('image', models.ImageField(blank=True, upload_to=mainapp.utilities.get_timestamp_path)),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='тэг статьи')),
                ('add_datatime', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальность статьи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
                ('hub', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.hub', verbose_name='Хаб')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-add_datatime'],
            },
        ),
    ]
