# Generated by Django 3.2.8 on 2021-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_comment',
            field=models.IntegerField(default=0, verbose_name='количество комментариев'),
        ),
        migrations.AddField(
            model_name='article',
            name='count_dislike',
            field=models.IntegerField(default=0, verbose_name='количество дизлайков'),
        ),
        migrations.AddField(
            model_name='article',
            name='count_like',
            field=models.IntegerField(default=0, verbose_name='количество лайков'),
        ),
        migrations.AddField(
            model_name='article',
            name='count_sub_comment',
            field=models.IntegerField(default=0, verbose_name='количество сабкомментариев'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
