# Generated by Django 3.2.8 on 2021-10-27 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.utilities


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonsInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название кнопки')),
                ('include_html_file_name', models.CharField(max_length=100, verbose_name='html файл')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('image', models.ImageField(blank=True, upload_to=mainapp.utilities.get_timestamp_path)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активация комментария')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления комментария')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=22, verbose_name='АйПи посетителя')),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='like_status',
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AddField(
            model_name='likes',
            name='status',
            field=models.CharField(choices=[('DZ', 'Дизлайк'), ('UND', 'Не установлено'), ('LK', 'Лайк')], default='UND', max_length=3, verbose_name='Статус лайка статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('DR', 'Черновик'), ('MD', 'На модерации'), ('RC', 'Требует исправления'), ('PB', 'Опубликована'), ('AR', 'В архиве')], default='DR', max_length=2, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.TextField(max_length=250, verbose_name='Предпросмотр'),
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст подкомментария')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активация комментария')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления ответа')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор подкомментария')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Подкомментарий',
                'verbose_name_plural': 'Подкомментарии',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=2, verbose_name='Краткое название')),
                ('name', models.CharField(max_length=50, verbose_name='Название статуса')),
                ('name_plural', models.CharField(max_length=50, verbose_name='Название раздела в ЛК (мн.число)')),
                ('buttons', models.ManyToManyField(to='mainapp.ButtonsInProfile', verbose_name='Кнопки для этого статуса в ЛК')),
            ],
        ),
        migrations.CreateModel(
            name='Art_Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Статья')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.hosts', verbose_name='адрес посетителя')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_status_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.articlestatus', verbose_name='Статус публикации (новый)'),
        ),
    ]
