# Generated by Django 3.2.8 on 2021-10-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hab',
            new_name='Hub',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='hab',
            new_name='hub',
        ),
    ]
