# Generated by Django 3.2.8 on 2021-11-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_audio',
            field=models.TextField(blank=True, verbose_name='Текст аудио'),
        ),
    ]
