# Generated by Django 3.2.8 on 2021-10-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.utilities


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('image', models.ImageField(blank=True, upload_to=mainapp.utilities.get_timestamp_path)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активация комментария')),
                ('add_datatime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
