# Generated by Django 3.2.8 on 2021-10-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.hab', verbose_name='Хаб'),
        ),
    ]
