# Generated by Django 3.2.8 on 2021-10-10 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211010_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_datatime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время добавления'),
        ),
    ]
