# Generated by Django 3.2.8 on 2021-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211107_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='count_dislike',
        ),
        migrations.RemoveField(
            model_name='article',
            name='count_like',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='like_and_dislike',
            field=models.ManyToManyField(to='mainapp.Likes'),
        ),
    ]
