# Generated by Django 3.2.8 on 2021-11-13 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20211113_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='hub',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.hub', verbose_name='Хаб'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
