# Generated by Django 3.2.8 on 2021-11-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211107_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_and_dislike',
        ),
        migrations.AddField(
            model_name='article',
            name='count_dislike',
            field=models.IntegerField(default=0, verbose_name='количество дизлайков'),
        ),
        migrations.AddField(
            model_name='article',
            name='count_like',
            field=models.IntegerField(default=0, verbose_name='количество лайков'),
        ),
        migrations.AddField(
            model_name='likes',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.article'),
            preserve_default=False,
        ),
    ]
