# Generated by Django 3.2.8 on 2021-11-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='_mainapp_comment_comments_+', to='mainapp.Comment'),
        ),
    ]
