# Generated by Django 3.2.8 on 2021-11-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_sorting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status_like_dislike',
            field=models.CharField(default='UND', max_length=8, verbose_name='рейтинг'),
        ),
    ]
