# Generated by Django 3.2.8 on 2021-11-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211107_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='count_comment',
            new_name='count_comment_and_sub_comment',
        ),
        migrations.RemoveField(
            model_name='article',
            name='count_sub_comment',
        ),
    ]
