# Generated by Django 3.2.8 on 2021-11-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_raiting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
    ]
