# Generated by Django 3.2.8 on 2021-11-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211113_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='article_view_count',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='article_author_view_count',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='hub_view_count',
        ),
    ]
