# Generated by Django 3.2.8 on 2021-11-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211102_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='Имя посетителя')),
                ('host', models.CharField(max_length=32, verbose_name='IP посетителя')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Статья')),
            ],
        ),
        migrations.DeleteModel(
            name='Art_Visits',
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
    ]
