# Generated by Django 3.2.8 on 2021-11-09 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211109_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment'),
        ),
    ]
