# Generated by Django 3.2.8 on 2021-11-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211113_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='view_count',
            new_name='article_view_count',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='article_author_view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров авторов'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='hub_view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров хабов'),
        ),
    ]
