# Generated by Django 3.2.8 on 2021-11-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_comment',
        ),
    ]
