# Generated by Django 3.2.8 on 2021-11-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_comment_sub_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='count_comment_and_sub_comment',
            new_name='count_comment',
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
