# Generated by Django 3.2.8 on 2021-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
    ]
