# Generated by Django 3.2.8 on 2021-10-28 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Статус прочтения')),
                ('action', models.TextField(verbose_name='Текст')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('target', models.TextField(verbose_name='Цель')),
                ('article_id', models.PositiveIntegerField(verbose_name='ID статьи')),
                ('comment_id', models.PositiveIntegerField(null=True, verbose_name='ID комментария')),
                ('subcomment_id', models.PositiveIntegerField(null=True, verbose_name='ID подкомментария')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время уведомления')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
