# Generated by Django 3.2.8 on 2021-11-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='название чата')),
            ],
        ),
        migrations.AddField(
            model_name='intergalacticuser',
            name='chats',
            field=models.ManyToManyField(to='authapp.Chat', verbose_name='Чаты пользователя'),
        ),
    ]
