# Generated by Django 3.2.8 on 2021-11-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_notificationmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='article_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID статьи'),
        ),
    ]
