# Generated by Django 3.2.8 on 2021-10-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_intergalacticuser_about_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntergalacticUser',
        ),
    ]
