# Generated by Django 3.2.8 on 2021-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_notificationmodel_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intergalacticuser',
            name='send_to_email',
            field=models.BooleanField(default=True, verbose_name='Уведомления на почту'),
        ),
    ]
