# Generated by Django 3.2.8 on 2021-11-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUserStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authapp.intergalacticuser', verbose_name='Пользователь')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
            ],
        ),
    ]
