# Generated by Django 3.2.8 on 2021-11-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211117_1155'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='complaintmessage',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='complaintmessage',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Статья'),
        ),
    ]
