# Generated by Django 3.2.8 on 2021-11-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_blockeduserstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUserStatus',
        ),
    ]
