# Generated by Django 3.2.8 on 2021-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='text',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
    ]
