# Generated by Django 3.2.8 on 2021-11-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_articlemessage_moderator'),
        ('moderation', '0002_complaint_complaintmessage'),
    ]

    operations = [
    ]
