# Generated by Django 3.2.8 on 2021-11-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20211114_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='user',
        ),
    ]
