# Generated by Django 3.2.8 on 2021-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_rename_name_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='was_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
