# Generated by Django 3.2.8 on 2021-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0002_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
