# Generated by Django 3.2.8 on 2021-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0003_userbalance_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Баланс'),
        ),
    ]
