# Generated by Django 3.2.8 on 2021-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0004_alter_userbalance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Статус прочтения'),
        ),
    ]
