# Generated by Django 3.2.8 on 2021-11-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0005_transaction_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Монеты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('DONE', 'Выполнена'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=9, verbose_name='Статус лайка статьи'),
        ),
    ]
